LEAGUE_SIZE = 10
VERBOSE = True

TEAM_NAMES = [
    "Jacksonville",
    "Minnesota",
    "Philadelphia",
    "Houston",
    "Los Angeles",
    "Baltimore",
    "Denver",
    "Seattle",
    "New England",
    "Carolina",
    "Pittsburgh",
    "Kansas City",
    "Chicago",
    "Atlanta",
    "Arizona",
    "Green Bay",
    "New York",
    "Tennessee",
    "Detroit",
    "Buffalo",
    "New Orleans",
    "San Francisco",
    "Washington",
    "Cleveland",
    "Cincinnati",
    "Dallas",
    "Indianapolis",
    "Miami",
    "Oakland",
    "Tampa Bay",
]
